sites/all/modules/hr/hr_events/hr_events.module, sites/all/modules/hr/hr_events/js/hr_events.js
Hi @guillaumev. Kindly have a look, I tested this on my local dev and works well. Cheers,
=> #47 Fixed Calendar entries - make end date update to the start date

sites/all/modules/hr/hr_operations/hr_operations.views_default.inc
I dropped the GeoJSON view, created another using the GeoJSON view display ...
=> Martin #84 recover geojson display

sites/all/modules/hr/hr_bundles/hr_bundles.views_default.inc
@pcambra kindly have a look. I dropped the existing views and created new ones, using the GeoJSON Feed display.
=> #119 Recover broken view displays in hr_bundles

sites/all/modules/hr/hr_admin/hr_admin.module
Messed up with some commits and bringing them back
=> Issue #56 - Removed unneeded code

sites/all/modules/hr/hr_admin/hr_admin.info, sites/all/modules/hr/hr_admin/hr_admin.views_default.inc
Updated the authors view with new fields and data export
@pcambra or @MartinMaritim Check if it's okay
=> 56_content_listing

sites/all/modules/hid/hid_profiles/templates/contacts_view.html
=> #223 Fixed spelling

sites/all/modules/hr/hr_operations/hr_operations.module
HRINFO-399: Add Ecuador, remove Nepal
HRINFO-390: Link to French version
=> Fix operations on homepage

sites/all/modules/hr/hr_documents/hr_documents.features.field_base.inc, sites/all/modules/hr/hr_documents/hr_documents.features.field_instance.inc, sites/all/modules/hr/hr_documents/hr_documents.views_default.inc
- Change label to: "Original Publication Date"
- Default the field to empty
- Make the field mandatory
- Add help text
=> Mark publication data as mandatory

sites/all/modules/contrib/phone/phone.module, sites/all/modules/hdx/hdx_datasets/hdx_datasets.module, sites/all/modules/hdx/hdx_datasets/js/hdx_datasets.js, sites/all/modules/hdx/hdx_datasets/templates/hdx-datasets-powered-by.tpl.php, sites/all/modules/hr/hr_api/hr_api.info, sites/all/modules/hr/hr_api/hr_api.strongarm.inc, sites/all/modules/hr/hr_bundles/test/bundle_map/index.html, sites/all/modules/hr/hr_datasets/hr_datasets.module, sites/all/modules/hr/hr_datasets/plugins/restful/node/hr_dataset/1.0/hr_dataset__1_0.inc, sites/all/modules/hr/hr_disasters/hr_disasters.views_default.inc, sites/all/modules/hr/hr_documents/hr_documents.features.field_base.inc, sites/all/modules/hr/hr_documents/hr_documents.features.field_instance.inc, sites/all/modules/hr/hr_documents/hr_documents.strongarm.inc, sites/all/modules/hr/hr_documents/hr_documents.views_default.inc, sites/all/modules/hr/hr_events/hr_events.features.field_instance.inc, sites/all/modules/hr/hr_events/hr_events.info, sites/all/modules/hr/hr_events/hr_events.views_default.inc, sites/all/modules/hr/hr_infographics/hr_infographics.features.field_instance.inc, sites/all/modules/hr/hr_infographics/hr_infographics.views_default.inc, sites/all/themes/humanitarianresponse/templates/system/page.tpl.php
=> Go live 20/5/2016

sites/all/modules/hr/hr_operations/hr_operations.module
The second try I made Ethiopia start with a capital E.
=> Changed Fiji to Ethiopia and removed Ecuador.

sites/all/modules/hr/hr_layout/hr_layout.module
Change Documents to Documents, Maps, & Assessments HRINFO-375
=> Change Documents Block on Homepage HRINFO-375

sites/all/modules/hr/hr_layout/hr_layout.module
=> Changed Maps to Maps/Infographics

sites/all/modules/hr/hr_events/hr_events.module
This goes with https://github.com/UN-OCHA/tools-ansible/pull/48 (already applied to staging)
=> [OPS-5362] Allow optional credentials to be passed to the snap service endpoint.

sites/all/modules/hr/hr_events/hr_events.module
@left23 I didn't have push access to the repo so I'm sending this your way to merge and maybe deploy to staging for a test.
=> OPS-5362: use Snap Service to generate PDFs

sites/all/modules/hr/hr_events/hr_events.module, sites/all/themes/ocha_basic/tpl/page.tpl.php
See [OPS-5362](https://humanitarian.atlassian.net/browse/OPS-5362) for discussion
1. remove pull-right class from div surrounding print logo
2. add cd-container class
3. set styles inline for parent div and image for positioning
=> OPS-5362 Print logo for PDF

html/sites/all/modules/hr/hr_api/hr_api.module
Note that the new format for hr_api_webhooks is:
$conf['hr_api_webhooks']['hid'] = array(
'url' => 'https://api.dev.humanitarian.id/api/v2/webhooks/hrinfo',
'types' => array(
'node' => array(
'hr_operation' => 'operations:1.0',
'hr_bundle' => 'bundles:1.0',
'hr_office' => 'offices:1.0',
),
'taxonomy_term' => array(
'hr_organization' => 'organizations:1.0',
)
),
'secret' => '123456'
);
=> HRINFO-963 - Fixed issue with drupal_set_message not working

html/sites/all/modules/hr/hr_events/hr_events.features.field_instance.inc, html/sites/all/modules/hr/hr_events/hr_events.info, html/sites/all/modules/hr/hr_events/hr_events.module, html/sites/all/modules/hr/hr_events/hr_events.panelizer.inc, html/sites/all/themes/ocha_basic/includes/form.inc, html/sites/all/themes/ocha_basic/tpl/forms/node-edit--hr_event.tpl.php
https://humanitarian.atlassian.net/browse/HRINFO-991
Restores the address field for events, removed in the form rework.
Also includes the template suggestion for the office form.
=> Hrinfo 991 re enable address field for events

html/sites/all/modules/hr/hr_assessments/hr_assessments.features.field_instance.inc, html/sites/all/modules/hr/hr_documents/hr_documents.features.field_instance.inc, html/sites/all/modules/hr/hr_events/hr_events.features.field_instance.inc, html/sites/all/modules/hr/hr_fundings/hr_fundings.features.field_instance.inc, html/sites/all/modules/hr/hr_infographics/hr_infographics.features.field_instance.inc, html/sites/all/modules/hr/hr_news/hr_news.features.field_instance.inc, html/sites/all/modules/hr/hr_pages/hr_pages.features.field_instance.inc
https://humanitarian.atlassian.net/browse/HRINFO-986
=> [HRINFO-986] change error settings for entityreference_prepopulate

html/sites/all/modules/hr/hr_core/hr_core.install
https://humanitarian.atlassian.net/browse/HRINFO-995
One of the fields we removed from the forms has some wrong data in it. This updates that link.
=> [HRINFO-995] update links in database

html/sites/all/themes/ocha_basic/tpl/forms/node-edit--hr_assessment.tpl.php, html/sites/all/themes/ocha_basic/tpl/forms/node-edit--hr_document.tpl.php, html/sites/all/themes/ocha_basic/tpl/forms/node-edit--hr_event.tpl.php, html/sites/all/themes/ocha_basic/tpl/forms/node-edit--hr_infographic.tpl.php
https://humanitarian.atlassian.net/browse/HRINFO-998
Add `t()` function for strings in template.
=> [HRINFO-998] make template strings translatable

html/sites/all/modules/custom/ocha_assessments/component/ocha-assessments-list.js, html/sites/all/modules/custom/ocha_assessments/component/ocha-assessments-map.js, html/sites/all/modules/custom/ocha_assessments/component/ocha-assessments-table.js
for cd-filter component
Result should be no visible change
=> AR-184 regenerate web components after renaming selectors on AR

html/sites/all/modules/hr/hr_reliefweb/hr_reliefweb.module
https://humanitarian.atlassian.net/browse/HRINFO-1007
Also, removes references to Vulnerable groups, but I don't think the function they're removed from is actually being used. Flagged as a candidate for later removal.
=> [HRINFO-1007] remove url limit for rss

html/sites/all/modules/hr/hr_layout/hr_layout.pages_default.inc
https://humanitarian.atlassian.net/browse/HRINFO-1006
Removes pane display for HID video.
=> [HRINFO-1006] remove hid video from homepage

html/sites/all/modules/hr/hr_core/hr_core.module
https://humanitarian.atlassian.net/browse/HRINFO-1008
Looks like the file names have been missing for a while - previously, there would have been a file title, but I haven't traced when that was removed. The fallback to the file-name wasn't working. Fixed now.
Also cleans up some coding standards stuff.
=> [HRINFO-1008] restore missing file names

composer.patches.json, html/sites/all/modules/contrib/cors/cors.module, html/sites/all/modules/hr/hr_documents/src/Plugin/resource/RestfulEntityNodeDocuments.php
https://humanitarian.atlassian.net/browse/HRINFO-1019
=> [HRINFO-1019] avoid pdf previews for non-pdfs

html/sites/all/modules/hr/hr_core/hr_core.install
=> Hrinfo 1012 4 contacts feature part 4

PATCHES/ops-6982-robot-searches.patch, composer.patches.json
I may have done some live editing on prod to make this change, too.
=> [OPS-6982] Discourage bots from blowing up search pages. Reprise.

.travis.yml, composer.json, composer.lock, docker/Dockerfile, docker/policy.xml
=> [HOTFIX] Commit the policy.xml file that we try to copy, so the copy does not fail.

html/sites/all/modules/hr/hr_core/hr_core.module, html/sites/all/themes/ocha_basic/includes/form.inc, html/sites/all/themes/ocha_basic/includes/view.inc, html/sites/all/themes/ocha_basic/template.php
Fix some niggling recurrent errors and some coding standards that were pointed out at the same time.
=> [HRINFO-1033] fix small errors and coding standards

README.md, html/sites/all/modules/access/acc_applications/acc_applications.features.field_instance.inc, html/sites/all/modules/access/acc_incidents/acc_incidents.features.field_instance.inc, html/sites/all/modules/contrib/pni/panels_newrelic_insight.module, html/sites/all/modules/hr/hr_bundles/hr_bundles.module, html/sites/all/modules/hr/hr_core/hr_core.module, html/sites/all/modules/hr/hr_documents/plugins/content_types/hr_documents_key_documents.inc, html/sites/all/modules/hr/hr_events/hr_events.features.field_instance.inc, html/sites/all/modules/hr/hr_infographics/hr_infographics.features.field_instance.inc, html/sites/all/modules/hr/hr_pages/hr_pages.module
More minor but noisy issues. And adding some troubleshooting info to the README file.
https://humanitarian.atlassian.net/browse/HRINFO-1035
=> [HRINFO-1035] status page warnings, log errors and coding standards

html/sites/all/modules/custom/ocha_assessments/component/ocha-assessments-map.js, html/sites/all/modules/custom/ocha_assessments/ocha_assessments.module, html/sites/all/modules/hr/hr_core/hr_core.module
https://github.com/UN-OCHA/assessmentregistry8-site/pull/226 
and 
https://www.flowdock.com/app/unocha/hr-info/threads/e_WnK-DW5p1vrk7slxnFDTO7NoU
=> [HRINFO-1037] fix typo for maps and minor UX improvements

html/sites/all/modules/hdx/hdx_datasets/images/logo-hdx.svg, html/sites/all/modules/hdx/hdx_datasets/templates/hdx-datasets-powered-by.tpl.php
https://humanitarian.atlassian.net/browse/HRINFO-1060
Not sure the previous link to the image was ever working, but here's a new image and a new path.
=> [HRINFO-1060] restore hdx logo

composer.json, composer.lock, symfony.lock
https://www.flowdock.com/app/unocha/hr-info/threads/5dk_q9FtDrnL_KEA7O1Zeeteomm
to accompany https://github.com/UN-OCHA/hrinfo-site/pull/1049
=> [OPS-7634] add registry rebuild module

composer.json, composer.lock, symfony.lock
https://humanitarian.atlassian.net/browse/HRINFO-1066
=> [HRINFO-1066] restore spatial_import module

.github/workflows/docker-build-image.yml
We're all grown-ups here. Plus it's shorter to type.
=> Rename master to main.

html/sites/all/themes/ocha_basic/package-lock.json, html/sites/all/themes/ocha_basic/package.json, html/sites/all/themes/radix/package.json
These had got a long way behind: https://github.com/UN-OCHA/hrinfo-site/security/dependabot
=> Dependabot updates

html/sites/all/modules/hr/hr_layout/hr_layout.module, html/sites/all/modules/hr/hr_layout/hr_layout.pages_default.inc
As per https://humanitarian.atlassian.net/browse/HRINFO-1079, removes two blocks from homepage, removes 3 links and updates another.
=> [HRINFO-1079] update homepage blocks

html/sites/all/modules/hr/hr_core/hr_core.module
https://humanitarian.atlassian.net/browse/HRINFO-1081
=> [HRINFO-1081] use node title for custom dimension4 for operations

.github/workflows/docker-build-image.yml
Please merge once reviewed, the stack and Jenkins changes are already applied across all environments.
=> [OPS-7896] Use the unified build method.

docker/Dockerfile
Reverts UN-OCHA/hrinfo-site#1112
This is now done in the base image and soon in AWS WAF.
=> Revert "[OPS-7987] add PetalBot to bad bots list"

composer.json, composer.lock, html/sites/all/modules/contrib/user_expire/LICENSE.txt, html/sites/all/modules/contrib/user_expire/user_expire.admin.inc, html/sites/all/modules/contrib/user_expire/user_expire.info, html/sites/all/modules/contrib/user_expire/user_expire.install, html/sites/all/modules/contrib/user_expire/user_expire.module, html/sites/all/modules/contrib/user_expire/user_expire.rules.inc, html/sites/all/modules/contrib/user_expire/user_expire.test, html/sites/all/modules/contrib/user_expire/user_expire.views.inc, symfony.lock
https://humanitarian.atlassian.net/browse/OPS-7459
This adds the user_expire module but doesn't enable it or configure it (the expiry settings are all 'off' by default until configured otherwise).
=> [OPS-7459] include user_expire

html/sites/all/libraries/simplepie/simplepie.compiled.php
https://humanitarian.atlassian.net/browse/HRINFO-1107
=> [HRINFO-1107] bump simplepie version

composer.json, composer.lock, html/sites/all/modules/contrib/readonlymode/LICENSE.txt, html/sites/all/modules/contrib/readonlymode/README.txt, html/sites/all/modules/contrib/readonlymode/readonlymode.info, html/sites/all/modules/contrib/readonlymode/readonlymode.install, html/sites/all/modules/contrib/readonlymode/readonlymode.module, symfony.lock
Do not enable the module, this can be done manually to check if and how it works.
=> [OPS-8042] Add readonlymode module to provide a read-only Drupal 7 after Drupal 9 launch.

html/sites/all/modules/hr/hr_core/hr_core.module
=> feat: expose panels info

.github/workflows/composer-update.yml
Refs: OPS-8436
Feels like the next step...
=> chore: run periodic updates

html/sites/all/modules/hr/hr_core/hr_core.module
=> fix: bail earlier if we don't have field_collection_item

html/sites/all/modules/hr/hr_notifications/hr_notifications.rules_defaults.inc
=> feat: update mail text

html/sites/all/modules/contrib/daterangepicker/css/daterangepicker.css, html/sites/all/modules/contrib/daterangepicker/daterangepicker.info, html/sites/all/modules/contrib/daterangepicker/daterangepicker.install, html/sites/all/modules/contrib/daterangepicker/daterangepicker.module, html/sites/all/modules/contrib/daterangepicker/js/daterangepicker.js
Not sure how the submodule got included again. Removing it.
=> chore: replace git submodule with module

PATCHES/core-HRINFO-1274.patch, composer.patches.json, html/includes/common.inc
=> bug: Make sure there is an entity

PATCHES/core-HRINFO-1274.patch, composer.patches.json, html/includes/common.inc, html/sites/all/modules/hr/hr_core/hr_core.install
=> bug: Use normal entity select

docker/Dockerfile
=> fix: pin composer version in dockerfile too

html/sites/all/modules/hr/hr_api/src/Plugin/resource/DataProvider/DataProviderOgMemberships.php, html/sites/all/modules/hr/hr_api/src/Plugin/resource/DataProviderOptimized.php, html/sites/all/modules/hr/hr_api/src/Plugin/resource/Field/ResourceFieldEntityTextCustom.php, html/sites/all/modules/hr/hr_api/src/Plugin/resource/ResourceCustom.php, html/sites/all/modules/hr/hr_api/src/Plugin/resource/RestfulFiles.php, html/sites/all/modules/hr/hr_api/src/Plugin/resource/fields/ResourceFieldEntityMinimal.php, html/sites/all/modules/hr/hr_assessments/src/Plugin/resource/DataProviderAssessments.php, html/sites/all/modules/hr/hr_disasters/src/Plugin/resource/RestfulEntityNodeDisasters.php, html/sites/all/modules/hr/hr_documents/src/Plugin/resource/DataProviderFieldFilesCollection.php, html/sites/all/modules/hr/hr_events/hr_events.drush.inc, html/sites/all/modules/hr/hr_locations/src/Plugin/resource/RestfulEntityTaxonomyTermLocations.php, html/sites/all/modules/hr/hr_operations/src/Plugin/resource/RestfulEntityNodeOperations.php, html/sites/all/modules/hr/hr_organizations/src/Plugin/resource/DataProviderOrganizations.php, html/sites/all/modules/hr/hr_tools/hr_tools.drush.inc
=> fix: phpcbf sorting

composer.json, composer.lock
This is to help people migrate off HR.info.
Refs: OPS-9382
=> feat: Add Redirect 404 module to redirect to RW Response on page not found.
