sites/all/modules/hr/hr_operations/hr_operations.features.field_base.inc
sites/all/modules/hr/hr_operations/hr_operations.features.field_instance.inc
sites/all/modules/hr/hr_operations/hr_operations.views_default.inc

Instead of creating another field for this, I reused the hid_access field, and added the "inactive" status, so HID will have to pull any operation that does not have "hid_access = inactive"

#79: added inactive status to hid_access field for operations

---

sites/all/modules/hr/hr_search/hr_search.install

Re enables 'field_infographic_type' under search api fields. When indexing is performed, the required facet 'Filter by Map/Infographic Type' will be enabled.
Reverting the hr_search feature results in the search listings to fail. For instance the page at /documents, /en/operations/iraq/documents, /operations/iraq/infographics.

Martin #282 map filter

---

sites/all/modules/hr/hr_documents/hr_documents.features.field_base.inc
sites/all/modules/hr/hr_documents/hr_documents.features.field_instance.inc
sites/all/modules/hr/hr_documents/hr_documents.strongarm.inc
sites/all/modules/hr/hr_documents/hr_documents.views_default.inc

- Clusters/Sectors: move on top of Coordination hubs
- Locations: Change name to Location(s)
- Change to Organization(s)
- Title: Type the original title of the document
- FIle(s): Attach the file to publish and specify the language of the document from the drop-down menu. It is best to publish only one file per record.
- Clusters/Sectors: Indicate the cluster(s)/sector(s) the document refers to.
- Location(s): Select from the menu the country(ies) the document is about. You can add more specific locations by selecting multiple layers (region, province, town).
- Organization(s): Type and select the source(s) of the document.
- Coordination hub: Click on the field and select the coordination hub(s) the document refers to (if any).
- Disasters: Click on the field and select the disaster(s) …

Small fixes to hr-document

---

sites/all/themes/humanitarianresponse/template.php
sites/all/themes/humanitarianresponse/templates/system/page.tpl.php

Fixed the footer link, which was generated as user/login and which robots were following, generating URLs such as https://www.humanitarianresponse.info/es/operations/ecuador/events/print/17026/2016-09/user/login?field_bundles_target_id_entityreference_filter=124037&field_coordination_hubs_target_id_entityreference_filter=All&field_event_category_target_id_entityreference_filter=82&field_location_target_id_entityreference_filter=All which are causing pgsql errors.

Fixed footer link

---

sites/all/modules/hr/hr_core/hr_core.install

Adds a deep purple profile for assessment and a dark teal for indicator.
This would need to be separately merged into each of the feature branches.
I am 99% sure that environment_indicator will apply the match with the lightest weight, so the default should be last. I've tightened up the hr_test regex, so it doesn't automagically apply to any unconfigured environment on mp03.

[OPS-1870] [OPS-1871] Add new environments to environment_indicator.

---

sites/all/modules/contrib/search_api_solr_overrides/LICENSE.txt
sites/all/modules/contrib/search_api_solr_overrides/README.txt
sites/all/modules/contrib/search_api_solr_overrides/search_api_solr_overrides.info
sites/all/modules/contrib/search_api_solr_overrides/search_api_solr_overrides.module
sites/all/modules/hr/hr_core/hr_core.install

There is a config snippet for the test site on disk already on MP03 at /srv/hrinfo/volumes/www/html/sites/default/settings.solr.php:
```
<?php
/**
* Settings specific to hrtest.
*/
$conf['search_api_solr_overrides'] = array(
'hr_solr' => array(
'name' => t('HRINFO Test Solr Server (Overridden)'),
'options' => array(
'host' => 'solr',
'port' => 8983,
'path' => '/solr/core0',
),
),
);
```
If this $conf variable is absent (as is currently the case on prod) then the module does nothing.

[OPS-1319] Install and enable search_api_solr_overrides, so we can set solr config per environment in settings.php.

---

sites/all/modules/hr/hr_reliefweb/js/hr_reliefweb_overview.js

innerText returns any empty string here in Firefox causing the select to not be properly populated. Changing it to innerHTML fixes the issue and works in IE & Chrome as well.

HRINFO-641 changed innerText to innerHTML to prevent firefox bug 

---

sites/all/modules/contrib/j2h/j2h.module

This PR fixes a superfluous line of code that makes HR.info 503 on PHP 7.1.6. Without it, it runs fine.
On a different note, why is this module in contrib? It's custom, from github, and unmaintained.

[HOTFIX] PHP7 Fatal: break statement outside switch. Safe to remove.

---

sites/all/modules/contrib/j2h/j2h.module

The module was not using the cache API correctly, so the data was never cached, which meant that cache_get never returned anything.

[HOTFIX] Correctly use cache_set() and specify the bin, so we can retrieve the stored data.

---

sites/all/modules/private_content_export/private_content_export.drush.inc
sites/all/modules/private_content_export/private_content_export.info
sites/all/modules/private_content_export/private_content_export.module
sites/all/modules/private_content_export/views/private_content_export.views_default.inc

Note that you need to revert the 'My Private Content' view after enabling this module, so that the attachment_1 display exists.

[OPS-3458] Custom (drush) module that can export all nodes selected by a view, with attached files.

---

sites/all/themes/ocha_basic/package-lock.json
sites/all/themes/ocha_basic/package.json

to prevent Browserslist: caniuse-lite version warning when running gulp.
`Browserslist: caniuse-lite is outdated. Please run next command npm update caniuse-lite browserslist`
Run `npm install` locally.

update cssnano package

---

html/sites/all/themes/ocha_basic/.sass-lint.yml
html/sites/all/themes/ocha_basic/gulpfile.js
html/sites/all/themes/ocha_basic/package-lock.json
html/sites/all/themes/ocha_basic/package.json
html/sites/all/themes/ocha_basic/sass/base/_base.scss

To correct dependency security issues
Run npm audit fix for some
Upgrade Gulp from 3 to 4 and refactor gulp tasks to reflect (based on work already done on ocha_basic)
This includes sass linting, but I commented this task out in the Gulp workflow so no errors are logged.

HRINFO-950 dependency updates and upgrade Gulp

---

html/includes/common.inc
html/sites/all/modules/contrib/redis/redis.path.inc

Redis module has its own path.inc which should be used *everywhere* by
core. However, our core path.inc is patched by path_alias_xt module and
this means that on order to get reliable operation, we *also* need to
patch the redis-provided path.inc version with the path_alias_xt fix.
The alternative is to install PECL runkit, but that has security
implications we would rather not deal with.

[OPS-5828][OPS-5687] Path patch.inc (even for redis)

---

html/sites/all/modules/hr/hr_assessments/src/Plugin/resource/RestfulEntityNodeAssessments.php

Also running strip_tags and trim to maintain consistency with the fields' original appearance as plain text fields.

OPS-6101 return plain value - not an array for text fields.

---

composer.lock
composer.patches.json
html/sites/all/modules/contrib/redis/PATCHES.txt
html/sites/all/modules/contrib/redis/lib/Redis/Cache/PhpRedis.php

This is a follow-up to https://github.com/UN-OCHA/hrinfo-site/pull/894 which *may* not be needed, now that the cache logic is better in redis 3.18.
Keeping it ready just in case we start running into cache-clear induced slowdowns again though.

[OPS-5482] Pick a dropped Redis patch (that aims to fix lockups on cache entry delete) up off the floor.

---

docker/Dockerfile
docker/custom/01-hrinfo.conf
docker/custom/02-hpc-ir.conf

Except (www.)?salahumanitaria.co which points at Colombia's own web
redirector and is no lomger handled by us.

[OPS-5482] Maintain nginx based redirects.

---

html/sites/all/modules/hr/hr_core/hr_core.module

https://humanitarian.atlassian.net/browse/HRINFO-1000
Related to https://humanitarian.atlassian.net/browse/HRINFO-949 and https://humanitarian.atlassian.net/browse/HID-1812
See the 'lock_language' setting in `hr_bundles.strongarm.inc`:
```
entity_translation_settings_node__hr_bundle:
default_language: xx-et-current
hide_language_selector: 0
exclude_language_none: 1
lock_language: 1
shared_fields_original_only: 0
```
and also for 'operations', but not for 'offices'.
(not sure what the default_language setting is there - perhaps setting it to English would be a fix for the HID issue)

[HRINFO-1000] remove language validation for clusters and operations

---

html/sites/all/themes/radix/package-lock.json
html/sites/all/themes/radix/package.json

radix only, update gulp to v4, run npm audit, follow advised dev dependency updates, 
Radix theme might not compile without changes to the gulp file (to suit gulp upgrade to v4) but is not needed right now. We can likely get away with not compiling it for a long time. Maybe forever.

OPS-6350 Radix dependency updates

---

docker/Dockerfile

My hope is that this will fix the intermittent production cron job fails.

[OPS-6585] Bump the docker image for a NewRelic segfault-on-long-tasks fix.

---

composer.json
composer.lock
html/sites/all/modules/contrib/memcache/LICENSE.txt
html/sites/all/modules/contrib/memcache/README.txt
html/sites/all/modules/contrib/memcache/dmemcache.inc
html/sites/all/modules/contrib/memcache/memcache-lock-code.inc
html/sites/all/modules/contrib/memcache/memcache-lock.inc
html/sites/all/modules/contrib/memcache/memcache.drush.inc
html/sites/all/modules/contrib/memcache/memcache.inc
html/sites/all/modules/contrib/memcache/memcache.info
html/sites/all/modules/contrib/memcache/memcache.install
html/sites/all/modules/contrib/memcache/memcache.module
html/sites/all/modules/contrib/memcache/memcache_admin/memcache.js
html/sites/all/modules/contrib/memcache/memcache_admin/memcache_admin.info
html/sites/all/modules/contrib/memcache/memcache_admin/memcache_admin.install
html/sites/all/modules/contrib/memcache/memcache_admin/memcache_admin.module
html/sites/all/modules/contrib/memcache/tests/memcache-lock.test
html/sites/all/modules/contrib/memcache/tests/memcache.test
html/sites/all/modules/contrib/memcache/tests/memcache6.test
html/sites/all/modules/contrib/memcache/tests/memcache_test.info
html/sites/all/modules/contrib/memcache/tests/memcache_test.module

This PR adds the memcache module. There is already a memcache container in the dev stack. After this code is deployed I will flip HR.info dev from redis to memcache for testing purposes. We'll see how we go for a week or two before touching prod (though this module is safe to merge to master and deploy to prod)

[OPS-6809] Add the memcache module. Do not enable it, that is managed in settings.php via Ansible.

---

html/sites/all/modules/hr/hr_events/hr_events.module

During latest Snap upgrade, we noticed the PDF footer has a visual regression. It was reproduced on Snap dev, Snap prod, and on my local running a similar image to prod.
I couldn't nail down exactly why the regression crept in, but I fixed it by supplying a more specific width to the PDF footer via the inline CSS. I commented it to explain the magic number.

SNAP-75: fix render issues with PDF footer

---

html/robots.txt

Robots appear to be creating searches that hit the PHP memory_limit. They also use resources that better spent on actual people, so let's just tell them to leave.
See also https://github.com/UN-OCHA/hrinfo-stack/pull/91

[OPS-6982] Tell robots to not perform searches. At all.

---

composer.patches.json
html/sites/all/modules/contrib/i18n/i18n.module

https://humanitarian.atlassian.net/browse/HRINFO-1029 
https://www.drupal.org/project/i18n/issues/2082573 suggests the error was caused by a module being enabled on the live site (which is why it's not common) and the solution is `drush rr`. That seemed to fix it, and this patch should mean we don't see it again.

[HRINFO-1029] patch i18n cache issue

---

docker/Dockerfile

* Try to improve memcached serialize() performance via igbinary.
* Contains a working imagemagick + ghostscript for PDF previews.

[OPS-7193][OPS-7265] Bump HR.info to the current PHP 7.3.26 develop base image.

---

html/sites/all/modules/hr/hr_bundles/hr_bundles.module

As part of https://humanitarian.atlassian.net/browse/HRINFO-1034, discovered that admins don't have the access to see revisions for node type hr_page - and perhaps others as well.
This PR gives that access to admins, putting now on the staging site so at least admins can look there to see what's going on. It might need some more changing and fine-tuning.

[HRINFO-1034] allow access to revisions for admins

---

html/sites/all/modules/hr/hr_core/hr_core.module
html/sites/all/modules/hr/hr_layout/hr_layout.module

Small change for the plus button - and a few changes for coding standards.
This removes the local link for assessments and doesn't add the AR one until the `hr_layout_ar_create_url` variable is set. (Most of that change is indentation, so adding `?w=1` to the url makes it more clear.)
I did try tidying it up with `theme('item_list')` but it added an extra div and I didn't want to complicate the dropdown js.
More to come for the assessment panel panes.

[HRINFO-1037] alter plus button link for assessments

---

html/sites/all/modules/custom/ocha_assessments/ocha_assessments.info
html/sites/all/modules/custom/ocha_assessments/ocha_assessments.module
html/sites/all/modules/custom/ocha_assessments/ocha_assessments.views.inc
html/sites/all/modules/custom/ocha_assessments/ocha_assessments.views_default.inc
html/sites/all/modules/custom/ocha_assessments/views/handlers/ocha_assessments_handler_field.inc
html/sites/all/modules/custom/ocha_assessments/views/plugins/ocha_assessments_plugin_query.inc
html/sites/all/modules/hr/hr_assessments/hr_assessments.module
html/sites/all/modules/hr/hr_bundles/hr_bundles.panelizer.inc
html/sites/all/modules/hr/hr_core/hr_core.module
html/sites/all/modules/hr/hr_operations/hr_operations.strongarm.inc

This adds a view for pane pulling assessments from AR. 
At the moment it only works for operations, we need to add a way to filter by 'local_groups' (clusters/sectors) to the AR api. Requires `drush fr hr_operations` for editors to be allowed to add it in panelizer. 
The pane is very basic and not configurable.
The results are different from the current pane as the sort order is different.
This should be fine to go with the deployment tomorrow - (i.e. feel free to merge it directly) but will need some tweaks afterwards. And to make the pane available for hr_bundles when we can (there are 6 operations currently using the assessments pane but nearly 500 bundles).

Hrinfo 1037 ar update

---

html/sites/all/modules/custom/ocha_assessments/views/plugins/ocha_assessments_plugin_query.inc

Not yet tested, but this should allow a block for hr_bundles when https://github.com/UN-OCHA/assessmentregistry8-site/pull/210 is deployed.

[HRINFO-1037] update views plugin for bundles

---

html/sites/all/modules/custom/ocha_assessments/ocha_assessments.module
html/sites/all/modules/custom/ocha_assessments/views/plugins/ocha_assessments_plugin_query.inc

With local groups added to AR, this reflects them on HRinfo - adjusts the api parameter and checks between operations and local_groups as appropriate.
This fixes the issue in https://www.flowdock.com/app/unocha/hr-info-registries/threads/Ye32agkyI8iA9l5cHtMlmasC9NW but needs a deploy on AR and reindexing there to happen first.

[HRINFO-1037] adjust api calls for local_groups

---

html/sites/all/modules/custom/ocha_assessments/views/plugins/ocha_assessments_plugin_query.inc

As noted in https://humanitarian.atlassian.net/browse/HRINFO-1047 the assessments blocks are empty.
This is due to a change in structure of the AR API results. This fixes it.

[HRINFO-1037] adjust structure of expected api results

---

html/sites/all/modules/custom/ocha_assessments/component/ocha-assessments-list.js
html/sites/all/modules/custom/ocha_assessments/component/ocha-assessments-map.js
html/sites/all/modules/custom/ocha_assessments/component/ocha-assessments-table.js

Ticket: AR-236
Note: better to view the files changed with `w=1`: https://github.com/UN-OCHA/hrinfo-site/pull/1026/files?w=1
This fixes an issue when selecting a filter in the `/list`, `/table` or `/map`.

[AR-236] Fix active filters

---

PATCHES/hrinfo-1057-file-alias-redirection.patch
composer.json
composer.lock
composer.patches.json
html/sites/all/modules/contrib/path_alias_xt/path_alias_xt.module

https://humanitarian.atlassian.net/browse/HRINFO-1057
Files without a path alias (we could open another ticket to work out *why* they don't have an alias) are all getting redirected to the same file.
Turns out this is caused by the `path_alias_xt` module (we could also have another ticket to remove that module - it turns 'edit' links etc into path aliases, which, for me, just makes it harder to discover the node number. Not sure if there are any benefits).
This adds a patch to stop looking for path aliases when it hasn't already found one and the path begins with 'file'.

[HRINFO-1057] remove redirection for files with no alias

---

html/sites/all/modules/hr/hr_locations/hr_locations.drush.inc

Drush command to fix admin levels needs to be run for all locations - this minor change avoids saving terms when nothing has changed.
It also logs cases where parents are zero - which shouldn't happen, and fixes coding standards.

[AR-240] streamline drush command

---

html/sites/all/modules/contrib/spatial_import/spatial_import.feeds.ShapefileParser.inc
html/sites/all/modules/contrib/spatial_import/spatial_import.feeds.inc
html/sites/all/modules/contrib/spatial_import/spatial_import.info
html/sites/all/modules/contrib/spatial_import/spatial_import.module
html/sites/all/modules/contrib/spatial_import/spatial_import.tw.inc

Both spellings of spatial_import module, (with underscore and with hyphen) provoke warnings that the other is missing:
https://jenkins.aws.ahconu.org/view/HR.info/job/hrinfo-dev-deploy/120/console
https://jenkins.aws.ahconu.org/view/HR.info/job/hrinfo-dev-deploy/121/console
This restores the contrib module as it was, and includes the new one through composer. Feels like it needs a clearer resolution.

[SCS-68] restore alternatively named spatial_import module

---

composer.patches.json
html/sites/all/modules/contrib/wysiwyg/editors/ckeditor.inc

Adds a patch to bump the accepted ckeditor version. And alphabeticizes the composer.json while we're there.

[OPS-7688] avoid ckeditor version warning

---

docker/Dockerfile

I think it would be useful to have a simpler way to define bad bots and bad IPs. Not sure if I want to keep overwriting things from the stack or from the repo though. Seems so 2021ish. :)

[OPS-7987] add PetalBot to bad bots list

---

docker/Dockerfile
docker/fastcgi_drupal.conf

fix: Drop in the D7 fastcgi_drupal config, so it can override the new default D8+ one.

---

.travis.yml

Refs: updates
Replaces the other changes tried in https://github.com/UN-OCHA/hrinfo-site/pull/1253 - though may have to remove the patch referred to in that issue too.

fix: pin composer version till preserve-paths package is updated

---

html/sites/all/modules/hr/hr_core/hr_core.module

Just redirect as usual for visitors not archive.org. And optimise the function a bit with an early return.
Refs: OPS-9290

fix: Ensure Drupal and varnish do not cache overridden content.
